### ISSUE TITLE
Doesn't load first option as selected one

### ISSUE THREAD

**Issue by Pixelalb** [AuHau/select-picker#11]
Is there a way to have the select display a custom label? (ie. send the label as title attribute value on the select)

**Comment by AuHau** [comment]
Hmmm I am not sure what do you mean... Can you please elaborate? 
If you look at the [documentation](http://picker.adam-uhlir.me/), then for example in the Basic Picker setup (this should be applicable in all scenarios) you can see that there is default option which is used as the placeholder for the picker...
```
<option value="" disabled hidden>Select value</option>
```

 Is it what you mean?

**Comment by Pixelalb** [comment]
I expect to see that value there: https://goo.gl/WqunKF
(shows "Select value" instead)

**Comment by AuHau** [comment]
Hmm you are expecting it right :-D 
Can you please make jsFiddle where this behavior is reproduced?

**Comment by Pixelalb** [comment]
https://jsfiddle.net/pixelalb/39xevwo9/1/

**Comment by AuHau** [comment]
Hey there!
So finally I managed to find some time and had a look on your issue and you are right, in the documentation this behavior is described, but in reality it is not like that.
I am working on fix, which should be released in few days, but until then you can customize the placeholder text through `texts` attribute in picker configuration.

**Comment by AuHau** [comment]
Fixed with #13 

Thanks taavs!
