### ISSUE TITLE
limit parameter on multiple option picker

### ISSUE THREAD

**Issue by leamasuero** [AuHau/select-picker#8]
Does the picker support a "limit" paramter so you cannot choose more than two options?

Thanks!

**Comment by AuHau** [comment]
Hey there,

currently unfortunately no. But it is good idea! I didn't think of this option... 
If you would have time and energy, you can send PR with this functionality, if not I will implement it eventually but right now I can't promise any timeline on that...

**Comment by AuHau** [comment]
Implemented and bundled with 0.3.1! :smiley:

**Comment by leamasuero** [comment]
Great! Thank you!
