### ISSUE TITLE
Unable to get value of select picker twice

### ISSUE THREAD

**Issue by adilkerimov** [AuHau/select-picker#9]
When I get value of selected option when 'sp-change' is called I can get correct value only once for each option.  When I try to select the same option .picker('get') returns value of first option.

Example:
$(document).on('sp-change','#ex-basic1',function(){
	var value = $(this).picker('get');
	console.log(value);
});

**Comment by AuHau** [comment]
Hey there,

hmm I am not able to reproduce your problem. I tried it with the event example on the documentation website and it works as expected (every time it returns an array with selected values). Do you have the picker in the single selection mode or multi selection mode? Can you please provide JSFiddle example where is the bug visible?

**Comment by adilkerimov** [comment]
Hi,

Here is my JSFiddle example - https://jsfiddle.net/nvq50tox/
I have it in the single selection mode.

**Comment by adilkerimov** [comment]
Hi,

Is there any other way to get correct value?

**Comment by AuHau** [comment]
Hey there,
I think you should be able to query the underlying Select HTML entity.
Check in the inspector for the structure and try that.
I'm currently traveling so this is all help I am able to give you right now

Dne 15. 6. 2017 4:12 napsal uživatel "adilkerimov" <notifications@github.com

**Comment by adilkerimov** [comment]
I use $(this).find('[selected = "selected"]').attr('value') instead of using API $('...').picker('get'). 
Perhaps it will be useful to those who have encountered this problem.

**Comment by AuHau** [comment]
Thanks,

I will bug fix it asap.

Adam Uhlíř

(Sent from mobile phone)

Dne 5. 7. 2017 0:57 napsal uživatel "adilkerimov" <notifications@github.com

**Comment by AuHau** [comment]
Sooooo after year and a half, I have come back to this problem (so much for ASAP, sorry... :sweat_smile:).

And I have tracked the problem to jQuery's problem, which is fixed since version 3.0.0, sooo if you have this problem, upgrade jQuery ;-) 

The problem seems with behavior of `:selected` pseudoselector, which somehow caches the result in and also in wrong way.

**Comment by nathanh2011** [comment]
I know this is old and considered closed but I have the same problem and am using jQuery 3.6.0.

Except I can change the value twice, then on the 3rd it seems to get 'stuck'.

Using $(this).find('[selected = "selected"]').attr('value') seems to work as expected though.

**Comment by AuHau** [comment]
I am sorry, but this project is quite old and I don't really have time to maintain it actively anymore. If you would have PR with a fix, I would be happy to review and merge, but I am not able to debug this anymore.
